### ISSUE TITLE
Repo search 

### ISSUE THREAD

**Issue by Ramblurr** [mandrade2/Codereader-issues#2]
Any plans to add the ability to search/grep all the files in a repo?

**Comment by mandrade2** [comment]
I'd love to do it, but I am laser focused on the foundations on the app right now. Still have many rough edges I want to cover before adding new things. 

You can search on a specific file though! Not the same but it's something. 

By the way, I am struggling to get feedback. Would you like to get codereader pro in exchange for any kind of feedback?

**Comment by mandrade2** [comment]
Hey @Ramblurrl, I implemented search via the Github Search API and after playing with it for some days I decided I won't be releasing it like this 😢 

First and biggest issue is that Github only indexes the default branch for your repo. It makes sense for them but for codereader I'd have to specify that the repo-level search bar is only searching on the default branch. Second issue and the one that seals the deal for me is that the search is not exhaustive. I searched for a common keyword in my neovim config files and it didn't find all occurrences. A search bar you can't trust is not a great addition.

Doing on-device search is something i'd love to get to one day. Will continue working on my next goals for now. Will update here when that changes!
